name: groc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Styling
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1

  # Maps & Location
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  latlong2: ^0.9.1

  # Utilities & Data
  csv: ^6.0.0
  http: ^1.5.0
  intl: ^0.19.0
  path_provider: ^2.1.6
  sqflite: ^2.4.3
  supabase_flutter: ^2.17.2

  path: ^1.9.1
  uuid: ^4.6.0
dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#44A45B"
  image: assets/images/logo.png
  android_12:
    color: "#44A45B"
    image: assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/items/