import 'product.dart';

final List<Product> sampleProducts = [
  Product(
    itemCode: 'IT001',
    itemName: 'Naturel Red Apple',
    unit: '1kg',
    category: 'Fresh Fruits & Vegetable',
    premiseCode: 'PR001',
    storeName: 'Lotus',
    price: 10.00,
    date: DateTime(2026, 8, 12),
  ),
  Product(
    itemCode: 'IT001',
    itemName: 'Naturel Red Apple',
    unit: '1kg',
    category: 'Fresh Fruits & Vegetable',
    premiseCode: 'PR002',
    storeName: 'NSK',
    price: 13.00,
    date: DateTime(2026, 8, 12),
  ),
  Product(
    itemCode: 'IT001',
    itemName: 'Naturel Red Apple',
    unit: '1kg',
    category: 'Fresh Fruits & Vegetable',
    premiseCode: 'PR003',
    storeName: 'Aeon',
    price: 15.00,
    date: DateTime(2026, 8, 12),
  ),
  Product(
    itemCode: 'IT002',
    itemName: 'Egg Chicken Red',
    unit: '4pcs',
    category: 'Dairy & Eggs',
    premiseCode: 'PR001',
    storeName: 'Lotus',
    price: 2.50,
    date: DateTime(2026, 8, 12),
  ),
  Product(
    itemCode: 'IT002',
    itemName: 'Egg Chicken Red',
    unit: '4pcs',
    category: 'Dairy & Eggs',
    premiseCode: 'PR002',
    storeName: 'NSK',
    price: 2.80,
    date: DateTime(2026, 8, 12),
  ),
];